version: '3.7'

name: dev_challenge_io

services:
  api:
    hostname: api.${DOMAIN_NAME}
    build: ./apps/api
    image: ghcr.io/snys98/challenge/api:latest
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api.entrypoints=http,https"
      - "traefik.http.routers.api.tls=true"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]  
      interval: 10s  
      timeout: 5s  
      retries: 3  
    networks: 
      - dev
  app:
    hostname: api.${DOMAIN_NAME}
    build: ./apps/app
    image: ghcr.io/snys98/challenge/app:latest
    ports:
      - 4000:4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.${DOMAIN_NAME}`)"
      - "traefik.http.routers.app.entrypoints=http,https"
      - "traefik.http.routers.app.tls=true"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 4000 || exit 1"]
      interval: 10s  
      timeout: 5s  
      retries: 3  
    networks:
      - dev
  scheduler:
    build: ./apps/scheduler
    image: ghcr.io/snys98/challenge/scheduler:latest
    networks:
      - dev

networks: 
    dev:
      external: true  
