version: '3.7'

services:
  api:
    image: ghcr.io/snys98/challenge/api:latest
    ports:
      - 3000:3000
    dns: 172.22.0.2
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:3000"]  
      interval: 10s  
      timeout: 5s  
      retries: 3  
    networks: 
      - dev
  app:
    image: ghcr.io/snys98/challenge/app:latest
    ports:
      - 4000:4000
    dns: 172.22.0.2
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:4000"]  
      interval: 10s  
      timeout: 5s  
      retries: 3  
    networks:
      - dev
  scheduler:
    image: ghcr.io/snys98/challenge/scheduler:latest
    dns: 172.22.0.2
    networks:
      - dev

networks: 
    dev:
      external: true  
