# step1: build
FROM node:18.12.1-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --depth 1
COPY . .
RUN npm run build

# step2: run
FROM node:18.12.1-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/dist ./dist
COPY package*.json ./
RUN npm install --production --depth 1
CMD [ "node", "./dist/main.js" ]
