http:
  middlewares:
    compress:
      compress: {}
  routers:
    api:
      rule: "Host(`api.dev.challenge.io`)"
      service: api
      entryPoints: ["http", "https"]
      tls: {}
    app:
      rule: "Host(`app.dev.challenge.io`)"
      service: app
      entryPoints: ["http", "https"]
      tls: {}
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
    app:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4000"
