# step1: build the app
FROM node:18.12.1-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --depth 1
COPY . .
RUN npm run build

# step2: copy the app and run it
FROM node:18.12.1-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/dist ./dist
COPY package*.json ./
RUN npm install --production --depth 1
RUN npm install -g serve
EXPOSE 4000
CMD [ "serve", "-s", "dist", "-l", "4000" ]
