# 指定 Node.js 的基础镜像
FROM node:18.12.1

# 设置工作目录
WORKDIR /usr/src/app

# 复制 package.json 和 package-lock.json 到工作目录
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制应用程序代码到工作目录
COPY . .

# 执行构建命令
RUN npm run build

# 暴露 API 端口
EXPOSE 3000

# 运行应用程序
CMD [ "npm", "run", "start:prod" ]
