name: Docker Image CI

on:
  push:
    branches: ["develop"]
    tags: ["release_*"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:
    inputs:
      ref_name:
        description: "ref to build(branch or tag)"
        required: true
      clean_ghcr:
        description: "whether to clean ghcr or not"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract image tag
        id: extract_image_tag
        run: |
          echo "start extract_image_tag"
          echo "github.event_name=${{ github.event_name }}"
          image_tag=""
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then  
            echo "match workflow_dispatch with ref_name=${{ github.event.inputs.ref_name }}"
            image_tag="${{ github.event.inputs.ref_name }}_$(date +'%Y%m%d%H%M%S')"
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/release_* ]]; then  
            echo "match ${GITHUB_REF}"
            image_tag="${GITHUB_REF/refs\/tags\/}"
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/develop" ]]; then  
            echo "match ${GITHUB_REF}"
            image_tag="dev_$(date +'%Y%m%d%H%M%S')"
          fi  
          echo "image_tag=$image_tag"
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
          if [[ $image_tag == release_* ]]; then  
            echo "is_release=true" >> "$GITHUB_OUTPUT"
          else  
            echo "is_release=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Test all packages
        run: npm i &&npm test

      - name: Build all Docker images
        if: success()
        shell: pwsh
        run: ./build_all.ps1

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for API
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sapia/api:${{ steps.extract_image_tag.outputs.image_tag }},${{ steps.extract_image_tag.outputs.is_release == 'true' && 'ghcr.io/${{ github.repository_owner }}/sapia/api:latest'  }}

      - name: Build and push Docker image for APP
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./apps/app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sapia/app:${{ steps.extract_image_tag.outputs.image_tag}},${{ steps.extract_image_tag.outputs.is_release == 'true' && 'ghcr.io/${{ github.repository_owner }}/sapia/app:latest' || '' }}
