name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
    tags: [ "release_*" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Determine image tag
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/release_"* ]]; then
          echo "IMAGE_TAG=${GITHUB_REF/refs\/tags\/}/" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/develop" ]]; then
          echo "IMAGE_TAG=dev_$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "IMAGE_TAG=${{ github.event.inputs.branch_name }}_$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        fi

    - name: test
      shell: pwsh
      run: npm test  

    - name: Build all Docker images
      shell: pwsh
      run: ./build_all.ps1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry  
      uses: docker/login-action@v2
      with:  
        registry: ghcr.io  
        username: ${{ github.repository_owner }}  
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build and push Docker image for API  
      uses: docker/build-push-action@v5
      with:  
        context: ./apps/api  
        push: true  
        tags: ghcr.io/${{ github.repository_owner }}/sapia/api:${{ env.IMAGE_TAG }}  
  
    - name: Build and push Docker image for APP  
      uses: docker/build-push-action@v5
      with:  
        context: ./apps/app  
        push: true  
        tags: ghcr.io/${{ github.repository_owner }}/sapia/app:${{ env.IMAGE_TAG }}
