name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies  
      run: npm install  
  
    - name: Run tests  
      run: npm test  

    - name: Build all Docker images
      shell: pwsh
      run: ./build_all.ps1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry  
      uses: docker/login-action@v1  
      with:  
        registry: ghcr.io  
        username: ${{ github.repository_owner }}  
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build and push Docker image for API  
      uses: docker/build-push-action@v2  
      with:  
        context: ./apps/api  
        push: true  
        tags: ghcr.io/${{ github.repository_owner }}/sapia/api:latest  
  
    - name: Build and push Docker image for APP  
      uses: docker/build-push-action@v2  
      with:  
        context: ./apps/app  
        push: true  
        tags: ghcr.io/${{ github.repository_owner }}/sapia/app:latest  

  manual-trigger:  
    needs: build  
    if: github.event_name == 'workflow_dispatch'  
    runs-on: ubuntu-latest  
    steps:  
    - name: Trigger the build job  
      run: echo "Triggering the build job"  
