name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
    tags: [ "release_*" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'ref to build(branch or tag)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Determine image tag
      id: image_tag
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/release_"* ]]; then  
          echo "::set-output name=image_tag::${GITHUB_REF/refs\/tags\/}/"   
        elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/develop" ]]; then  
          echo "::set-output name=image_tag::dev_$(date +'%Y%m%d%H%M%S')"   
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then  
          echo "::set-output name=image_tag::${{ github.event.inputs.ref_name }}_$(date +'%Y%m%d%H%M%S')"   
        fi  
        if [[ "${{ github.event.inputs.ref_name }}" == release* ]]; then  
          echo "::set-output name=is_release::true"   
        else  
          echo "::set-output name=is_release::false"   
        fi  


    - name: test
      shell: pwsh
      run: npm test  

    - name: Build all Docker images
      shell: pwsh
      run: ./build_all.ps1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry  
      uses: docker/login-action@v2
      with:  
        registry: ghcr.io  
        username: ${{ github.repository_owner }}  
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build and push Docker image for API  
      uses: docker/build-push-action@v5
      with:  
        context: ./apps/api  
        push: true  
        tags: |
          ghcr.io/${{ github.repository_owner }}/sapia/api:${{ steps.image_tag.outputs.image_tag }}
          ${{ steps.image_tag.outputs.is_release == 'true' && 'ghcr.io/${{ github.repository_owner }}/sapia/api:latest' || '' }}  

    - name: Build and push Docker image for APP  
      uses: docker/build-push-action@v5
      with:  
        context: ./apps/app  
        push: true  
        tags: |
          ghcr.io/${{ github.repository_owner }}/sapia/app:${{ steps.image_tag.outputs.image_tag}}
          ${{ steps.image_tag.outputs.is_release == 'true' && 'ghcr.io/${{ github.repository_owner }}/sapia/app:latest' || '' }}
